project:
  type: website
  output-dir: docs

website:
  title: "Gapminder Mini Site"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Life vs GDP"
        href: life-gdp.qmd
      - text: "Life vs Population"
        href: life-population.qmd
      - text: "Country Analysis"
        href: country.qmd

format:
  html:
    theme: cosmo
    toc: true
